name: Enable Automerge
on:
  pull_request:
    branches:
    - main
jobs:
  Enable-Automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Merge
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_ACTIONS }}
        run: gh pr merge --auto --merge ${{github.event.pull_request.html_url}}