name: Test
run-name: Test workflow

on:
  pull_request:
    branches:
      main

jobs:
  Initialize:
    name: Initialize
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab #v3.5.2
        
  CiStatus:
    name: CI Status
    needs: [ Initialize ]
    runs-on: [ ubuntu-latest ]
    steps:
      - name: CI status 
        run: echo CI status