name: Test
run-name: Test workflow

on:
  workflow_dispatch:

jobs:
  Initialize:
    name: ${{ matrix.builder.label }} generate metadata
    runs-on: [ ubuntu-latest ]
    outputs:
      descriptors: ${{ steps.setenv.outputs.descriptors }}
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab #v3.5.2

      - name: Setenv
        id: setenv
        run:
          descriptors='{"builders":[{"name":"abe-all","path":"abe/builders/abe-all","label":"abe-all (abe)"},{"name":"abe-core","path":"abe/builders/abe-core","label":"abe-core (abe)"},{"name":"businessrules-dcc","path":"businessrules/builders/businessrules-dcc","label":"businessrules-dcc (businessrules)"},{"name":"generic","path":"cicd-generic/builders/generic","label":"generic (cicd-generic)"},{"name":"example-image-name","path":"cicd/builders/example-image-name","label":"example-image-name (cicd)"},{"name":"asset-catalog","path":"controlplane/builders/asset-catalog","label":"asset-catalog (controlplane)"},{"name":"control-plane-engine","path":"controlplane/builders/control-plane-engine","label":"control-plane-engine (controlplane)"},{"name":"control-plane-ingress","path":"controlplane/builders/control-plane-ingress","label":"control-plane-ingress (controlplane)"},{"name":"control-plane-ui","path":"controlplane/builders/control-plane-ui","label":"control-plane-ui (controlplane)"},{"name":"esb-is","path":"esb/builders/esb-is","label":"esb-is (esb)"},{"name":"esb-msr","path":"esb/builders/esb-msr","label":"esb-msr (esb)"},{"name":"esb-msr-alpine","path":"esb/builders/esb-msr-alpine","label":"esb-msr-alpine (esb)"},{"name":"esb-msr-slim","path":"esb/builders/esb-msr-slim","label":"esb-msr-slim (esb)"},{"name":"mft-dcc","path":"mft/builders/mft-dcc","label":"mft-dcc (mft)"},{"name":"mws-runtime","path":"mws/builders/mws-runtime","label":"mws-runtime (mws)"},{"name":"mws-te","path":"mws/builders/mws-te","label":"mws-te (mws)"},{"name":"universalmessaging-server","path":"num/builders/universalmessaging-server","label":"universalmessaging-server (num)"},{"name":"universalmessaging-tools","path":"num/builders/universalmessaging-tools","label":"universalmessaging-tools (num)"},{"name":"terracotta-config-tool","path":"terracotta/builders/terracotta-config-tool","label":"terracotta-config-tool (terracotta)"},{"name":"terracotta-management-server","path":"terracotta/builders/terracotta-management-server","label":"terracotta-management-server (terracotta)"},{"name":"terracotta-server","path":"terracotta/builders/terracotta-server","label":"terracotta-server (terracotta)"},{"name":"terracotta-voter","path":"terracotta/builders/terracotta-voter","label":"terracotta-voter (terracotta)"},{"name":"businessrules","path":"businessrules/builders/businessrules","label":"businessrules (businessrules)"},{"name":"businessrules-acdl-all","path":"businessrules/builders/businessrules-acdl-all","label":"businessrules-acdl-all (businessrules)"},{"name":"businessrules-acdl-core","path":"businessrules/builders/businessrules-acdl-core","label":"businessrules-acdl-core (businessrules)"},{"name":"businessrules-mwsui","path":"businessrules/builders/businessrules-mwsui","label":"businessrules-mwsui (businessrules)"},{"name":"businessrules-runtime","path":"businessrules/builders/businessrules-runtime","label":"businessrules-runtime (businessrules)"},{"name":"businessrules-webui","path":"businessrules/builders/businessrules-webui","label":"businessrules-webui (businessrules)"},{"name":"wmdeployer","path":"deployer/builders/wmdeployer","label":"wmdeployer (deployer)"},{"name":"mft","path":"mft/builders/mft","label":"mft (mft)"},{"name":"abe-test","path":"abe/builders/abe-test","label":"abe-test (abe)"},{"name":"businessrules-test-abe","path":"businessrules/builders/businessrules-test-abe","label":"businessrules-test-abe (businessrules)"},{"name":"businessrules-test-assets-frt","path":"businessrules/builders/businessrules-test-assets-frt","label":"businessrules-test-assets-frt (businessrules)"},{"name":"businessrules-test-frt","path":"businessrules/builders/businessrules-test-frt","label":"businessrules-test-frt (businessrules)"},{"name":"businessrules-test-is-rest","path":"businessrules/builders/businessrules-test-is-rest","label":"businessrules-test-is-rest (businessrules)"},{"name":"businessrules-test-is-webui-rest","path":"businessrules/builders/businessrules-test-is-webui-rest","label":"businessrules-test-is-webui-rest (businessrules)"},{"name":"businessrules-test-mws-jasmine","path":"businessrules/builders/businessrules-test-mws-jasmine","label":"businessrules-test-mws-jasmine (businessrules)"},{"name":"businessrules-test-mws-rest","path":"businessrules/builders/businessrules-test-mws-rest","label":"businessrules-test-mws-rest (businessrules)"},{"name":"example-image-name-test","path":"cicd/builders/example-image-name-test","label":"example-image-name-test (cicd)"},{"name":"example-solution-test","path":"cicd/builders/example-solution-test","label":"example-solution-test (cicd)"},{"name":"mft-test","path":"mft/builders/mft-test","label":"mft-test (mft)"}]}'
          echo "descriptors=$descriptors" >> GITHUB_OUTPUT

  Test:
    name: ${{ matrix.builder.label }} generate metadata
    runs-on: [ ubuntu-latest ]
    needs: [ Initialize ]
    steps:
      - name: ECHO
        run: echo ${{ needs.Initialize.outputs.descriptors }}
      - name: ECHO2
        run: echo ${{ fromJSON(needs.Initialize.outputs.descriptors).builders.* }}


  MatrixJob:
    name: ${{ matrix.builder.label }} generate metadata
    runs-on: [ ubuntu-latest ]
    needs: [ Initialize ]
    strategy:
      matrix:
        builder: ${{ fromJSON(needs.Initialize.outputs.descriptors).builders.* }}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab #v3.5.2

      - name: Create metadata
        run: |
          metadataFile=$(pwd)/${{ matrix.builder.name }}.properties
          echo "${{ matrix.builder.name }}" > $metadataFile
          echo "Metadata created.."
      
      - name: Upload builder initial metadata
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 #v4.0.0
        with:
          name: builders-artifact
          path: ${{ github.workspace }}
